spring.sql.init.platform=postgresql
spring.datasource.platform=postgresql
db.num=1
db.url.0=jdbc:postgresql://postgres:5432/nacos_config
db.user.0=postgres
db.password.0=postgres
db.user=postgres
db.password=postgres
db.pool.config.driverClassName=org.postgresql.Driver
nacos.core.auth.server.identity.key=${NACOS_AUTH_IDENTITY_KEY}
nacos.core.auth.server.identity.value=${NACOS_AUTH_IDENTITY_VALUE}
nacos.core.auth.plugin.nacos.token.secret.key=${NACOS_TOKEN_SECRET}
